// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextCgm.DContentext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextCgm.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260418234908_AddCloudflareLogger")]
    partial class AddCloudflareLogger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextCgm.DataEntities.Cloudflare.CloudflareLogger", b =>
                {
                    b.Property<Guid>("CloudflareLoggerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CloudflareLoggerID");

                    b.ToTable("CloudflareLoggers");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Containers.DockerContainers", b =>
                {
                    b.Property<Guid>("DockerContainersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseImageContaierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CloudflareRecordId")
                        .HasColumnType("text");

                    b.Property<string>("ContainerIpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataBaseConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerLable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerStatusExeption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExposedPortLeft")
                        .HasColumnType("integer");

                    b.Property<int>("HostPortRight")
                        .HasColumnType("integer");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageNameInUse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceUserNameIdentifer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortRight")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserEntityID")
                        .HasColumnType("uuid");

                    b.HasKey("DockerContainersID");

                    b.HasIndex("UserEntityID");

                    b.ToTable("DockerContainers");
                });

            modelBuilder.Entity("NextCgm.DataEntities.DockerLogger", b =>
                {
                    b.Property<Guid>("DockerLoggerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerInstanceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerInstanceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExeptionMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExposedPortLeft")
                        .HasColumnType("integer");

                    b.Property<string>("FriendlyContanierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HostPortRight")
                        .HasColumnType("integer");

                    b.Property<string>("ImageNameInUse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DockerLoggerID");

                    b.ToTable("DockerLogger");
                });

            modelBuilder.Entity("NextCgm.DataEntities.DocumentDatabases.UserContainerDatabase", b =>
                {
                    b.Property<Guid>("UserContainerDatabaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserEntityID")
                        .HasColumnType("uuid");

                    b.HasKey("UserContainerDatabaseID");

                    b.ToTable("UserContainerDatabases");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.CountryList", b =>
                {
                    b.Property<Guid>("CountryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EmojiU")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Native")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Subregion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SubregionId")
                        .HasColumnType("integer");

                    b.Property<string>("Tld")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CountryListID");

                    b.ToTable("CountryLists");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.ProvinceStateList", b =>
                {
                    b.Property<Guid>("ProvinceStateListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryListID")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProvinceStateListID");

                    b.HasIndex("CountryListID");

                    b.ToTable("ProvinceStateLists");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.TimeZoneData", b =>
                {
                    b.Property<Guid>("TimeZoneDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("CountryListID")
                        .HasColumnType("uuid");

                    b.Property<int>("GmtOffset")
                        .HasColumnType("integer");

                    b.Property<string>("GmtOffsetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TzName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TimeZoneDataID");

                    b.HasIndex("CountryListID");

                    b.ToTable("TimeZoneData");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Nginx.NginxContainer", b =>
                {
                    b.Property<Guid>("NginxContainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClientMaxBodySizeMb")
                        .HasColumnType("integer");

                    b.Property<Guid>("DockerContainerID")
                        .HasColumnType("uuid");

                    b.Property<bool>("EnableWebSockets")
                        .HasColumnType("boolean");

                    b.Property<int>("ExternalPort")
                        .HasColumnType("integer");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InternalPort")
                        .HasColumnType("integer");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SslCertKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SslCertName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NginxContainerID");

                    b.HasIndex("DockerContainerID");

                    b.ToTable("NginxContainers");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Nginx.NginxRoutingRule", b =>
                {
                    b.Property<Guid>("NginxRoutingRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DockerContainerID")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListenPort")
                        .HasColumnType("integer");

                    b.Property<int>("TargetContainerPort")
                        .HasColumnType("integer");

                    b.HasKey("NginxRoutingRuleID");

                    b.HasIndex("DockerContainerID");

                    b.ToTable("NginxRoutingRules");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Nginx.NginxSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ContainerEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastErrorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NginxSyncLogID")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJsonSent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NginxSyncLogs");
                });

            modelBuilder.Entity("NextCgm.DataEntities.User.UserEntity", b =>
                {
                    b.Property<Guid>("UserEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiKeyForNightScout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CountryListID")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceStateListID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeZoneDataID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeZoneID")
                        .HasColumnType("uuid");

                    b.Property<string>("UserSubDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerificationCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VerificationCodeSentTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserEntityID");

                    b.HasIndex("ApiKeyForNightScout")
                        .IsUnique();

                    b.HasIndex("CountryListID");

                    b.HasIndex("ProvinceStateListID");

                    b.HasIndex("TimeZoneDataID");

                    b.HasIndex("UserSubDomain")
                        .IsUnique();

                    b.ToTable("UserEntities");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Containers.DockerContainers", b =>
                {
                    b.HasOne("NextCgm.DataEntities.User.UserEntity", "UserEntity")
                        .WithMany("DockerContainers")
                        .HasForeignKey("UserEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.ProvinceStateList", b =>
                {
                    b.HasOne("NextCgm.DataEntities.Locations.CountryList", "Country")
                        .WithMany("ProvinceStates")
                        .HasForeignKey("CountryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.TimeZoneData", b =>
                {
                    b.HasOne("NextCgm.DataEntities.Locations.CountryList", "Country")
                        .WithMany("TimeZones")
                        .HasForeignKey("CountryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Nginx.NginxContainer", b =>
                {
                    b.HasOne("NextCgm.DataEntities.Containers.DockerContainers", "Container")
                        .WithMany()
                        .HasForeignKey("DockerContainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Nginx.NginxRoutingRule", b =>
                {
                    b.HasOne("NextCgm.DataEntities.Containers.DockerContainers", "Container")
                        .WithMany()
                        .HasForeignKey("DockerContainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("NextCgm.DataEntities.User.UserEntity", b =>
                {
                    b.HasOne("NextCgm.DataEntities.Locations.CountryList", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextCgm.DataEntities.Locations.ProvinceStateList", null)
                        .WithMany("Users")
                        .HasForeignKey("ProvinceStateListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextCgm.DataEntities.Locations.TimeZoneData", null)
                        .WithMany("Users")
                        .HasForeignKey("TimeZoneDataID");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.CountryList", b =>
                {
                    b.Navigation("ProvinceStates");

                    b.Navigation("TimeZones");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.ProvinceStateList", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextCgm.DataEntities.Locations.TimeZoneData", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextCgm.DataEntities.User.UserEntity", b =>
                {
                    b.Navigation("DockerContainers");
                });
#pragma warning restore 612, 618
        }
    }
}
