using Medo;

namespace NextCgm.DataEntities
{
    public class DockerLogger
    {
        public Guid DockerLoggerID { get; set; } = Uuid7.NewUuid7();
        public string DockerInstanceID { get; set; } = string.Empty; // this is the unique identifier for the docker instance, and is used to map to the user's container and database. This can be a combination of the user's first name, last name, and a unique identifier, such as Dolfie1234567890, where Dolfie is the user's first name, and 1234567890 is a unique identifier for this user. This is used to create a unique API key and to identify the user in the system.
        public string DockerInstanceName { get; set; } = string.Empty; // this is the Fiendly URl adolfie-alpah.mydomain.com

        public string LogMessage { get; set; } = string.Empty; // this is the log message that is generated by the docker instance, and is used for debugging and monitoring purposes. This can include any information that is relevant to the operation of the docker instance, such as errors, warnings, status updates, etc.

        public bool IsError { get; set; } // this is a flag that indicates whether the log message is an error or not, and is used for filtering and sorting purposes. This can be set to true for error messages, and false for non-error messages.

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow; // this is the timestamp that indicates when the log message was created, and is used for sorting and filtering purposes. This can be set to the current UTC time when the log message is created, and can be used to track the history of the docker instance's operation over time.
        public string FriendlyContanierName { get; set; }
        public string ContainerStatus { get; internal set; }
        public string ImageNameInUse { get; internal set; }
        public string ExeptionMessage { get; internal set; }
        public int ExposedPortLeft { get; internal set; }
        public int HostPortRight { get; internal set; }
        public string DockerStatus { get; internal set; }
    }
}